---
version: "3.9"
services:
  # Use https://weaviate.io/developers/weaviate/current/getting-started/installation.html#customize-your-weaviate-setup
  # to create the weaviate configuration
  weaviate:
    container_name: osint_weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.18.0-alpha.0-e5d2456
    ports:
      - 8888:8080
    restart: unless-stopped
    depends_on:
      - t2v-transformers
      - i2v-neural
    volumes:
      - ./weaviate2:/var/lib/weaviate
      - /tmp/weaviate:/tmp/weaviate # Matches BACKUP_FILESYSTEM_PATH below
    environment:
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      IMAGE_INFERENCE_API: http://i2v-neural:8080
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: "backup-filesystem,text2vec-transformers,img2vec-neural"
      # Map backup filesystem path to volume if you want to access it outside the container
      BACKUP_FILESYSTEM_PATH: /tmp/weaviate
      CLUSTER_HOSTNAME: node1
  t2v-transformers:
    container_name: osint_t2v
    restart: unless-stopped
    ports:
      - 9999:8080
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-mpnet-base-v2
    environment:
      ENABLE_CUDA: "0"
  i2v-neural:
    container_name: osint_i2v
    restart: unless-stopped
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: "0"
  weaviate-console:
    container_name: weaviate_console
    image: semitechnologies/weaviate-console:latest
    ports:
      - 8000:80

  # To reset notebooks run: docker volume rm osint_notebooks
  # NOTE, you need to first build this docker image yourself, see the repo.
  jupyter:
    container_name: osint_jupyter
    profiles: ["jupyter"]
    restart: unless-stopped
    image: jupyter-weaviate-interface
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8181:8888
    volumes:
      - notebooks:/project

volumes:
  notebooks:
  weaviate:
